name:                todo-app-cli
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- text
- containers
- either

default-extensions:
- OverloadedStrings

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  todo-app-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todo-app-cli

tests:
  todo-app-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todo-app-cli
    - hspec
    - hspec-discover
    - QuickCheck
    - quickcheck-instances


verbatim:
  cabal-version: 3.0
